### PR TITLE
[date_utils] move from GT

### PR DESCRIPTION
**Pull request by Ritsz123**
Signed-off-by: Ritesh Khadse <r.khadse@flick2know.com>

## Description

move date_utils from GT app to Dart_core package

### CODE REVIEW

**Review by TusharFA — CHANGES_REQUESTED** [review]
Please change the commit message again following the proper conventions.
Please also update Readme file including basic details about DateTime util class.

**Comment by apgapg** [comment]
@TusharFA @Ritsz123 
Please include test cases.
Your PR results in heavy decrease in percentage of code coverage

**Review by TusharFA — CHANGES_REQUESTED** [review]
Please include all the test cases. Some are missing.

**Comment by apgapg** [comment]
https://app.codecov.io/gh/FieldAssist/fa_dart_core/compare/2/diff?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr%20comments&utm_term=FieldAssist#diff-bGliL3NyYy91dGlscy9kYXRlX3V0aWxzLmRhcnQ=

As per this, many functions test cases are missing.

For now you can keep only those which are required. I think most of them are not being used.
Also @TusharFA can we improving naming of functions. Previously I didnt write it properly.

**Pull request closed without merging**
